data_ingestion:
  test_size: 0.25
  random_state: 42

feature_engineering:
  n_components: 0.95 # Retain 95% of variance
  random_state: 42

model_building:
  kernel: "linear" # ((...) -> Any) | Literal['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'] = "rbf",
  degree: 5 # Int = 3,
  gamma: "auto" # float | Literal['scale', 'auto'] = "scale",
  coef0: 0 # Float = 0,
  tol: 0.010 # Float = 0.001,
  C: 50 # Float = 1,
  epsilon: 0.5 # Float = 0.1,
  shrinking: True # bool = True,
  cache_size: 200 # Float = 200,
  verbose: False # bool = False,
  max_iter: # Int = ...

