data_ingestion:
  test_size: 0.25
  random_state: 42

feature_engineering:
  n_components: 0.95 # Retain 95% of variance
  random_state: 42

model_building:
  param_grid:
    {
      "C": [0.1, 1, 10, 100],
      "epsilon": [0.01, 0.1, 0.5],
      "kernel": ["rbf"],
      "gamma": ["scale", "auto", 0.01, 0.1, 1],
    }
